import type { RecommendedModel } from './types'

export const RECOMMENDED_MODELS: RecommendedModel[] = [
  // ── Chat models ───────────────────────────────────────────
  {
    name: 'llama3.2:3b',
    displayName: 'Llama 3.2',
    parametersBillions: 3,
    sizeOnDisk: '~2 GB',
    minRAMGB: 4,
    tier: 'small',
    category: 'chat',
    description: 'Fast & lightweight — runs on almost anything',
    gpuRecommended: false,
  },
  {
    name: 'phi4-mini',
    displayName: 'Phi-4 Mini',
    parametersBillions: 3.8,
    sizeOnDisk: '~2.5 GB',
    minRAMGB: 6,
    tier: 'small',
    category: 'chat',
    description: 'Best reasoning at small size — recommended default',
    gpuRecommended: false,
  },
  {
    name: 'gemma3:4b',
    displayName: 'Gemma 3',
    parametersBillions: 4,
    sizeOnDisk: '~3 GB',
    minRAMGB: 6,
    tier: 'small',
    category: 'chat',
    description: 'Excellent instruction following, power-efficient',
    gpuRecommended: false,
  },
  {
    name: 'mistral:7b',
    displayName: 'Mistral 7B',
    parametersBillions: 7,
    sizeOnDisk: '~4.5 GB',
    minRAMGB: 8,
    tier: 'medium',
    category: 'chat',
    description: 'Higher quality — needs more RAM and benefits from GPU',
    gpuRecommended: true,
  },
  {
    name: 'phi4:14b',
    displayName: 'Phi-4',
    parametersBillions: 14,
    sizeOnDisk: '~10 GB',
    minRAMGB: 16,
    tier: 'large',
    category: 'chat',
    description: 'Near cloud-quality reasoning — needs 16GB+ RAM',
    gpuRecommended: true,
  },
  // ── Embedding models ──────────────────────────────────────
  {
    name: 'nomic-embed-text',
    displayName: 'Nomic Embed Text',
    parametersBillions: 0.137,
    sizeOnDisk: '~274 MB',
    minRAMGB: 4,
    tier: 'small',
    category: 'embedding',
    description: 'Fast, high-quality embeddings — recommended default',
    gpuRecommended: false,
  },
  {
    name: 'all-minilm',
    displayName: 'All-MiniLM',
    parametersBillions: 0.033,
    sizeOnDisk: '~67 MB',
    minRAMGB: 4,
    tier: 'small',
    category: 'embedding',
    description: 'Ultra-lightweight embeddings for constrained systems',
    gpuRecommended: false,
  },
]
